// Generated by Wrangler on Sat Jul 06 2024 14:08:34 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	INNGEST_SIGNING_KEY: string;
	INNGEST_EVENT_KEY: string;
	DATABASE_URL: string;
	DIRECT_DATABASE_URL: string;
	OPENAI_API_KEY: string;
}
