// Generated by Wrangler on Sun Jul 07 2024 21:59:51 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	INNGEST_DEV: string;
	INNGEST_SIGNING_KEY: string;
	INNGEST_EVENT_KEY: string;
	DATABASE_URL: string;
	OPENAI_API_KEY: string;
}
