// Generated by Wrangler on Fri Jul 05 2024 12:10:03 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	INNGEST_SIGNING_KEY: string;
	INNGEST_EVENT_KEY: string;
	DATABASE_URL: string;
}
